=== CSOIreland/PxStat/server/build/PxStat/Resources/Schemas/schema.global.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"title": {
			"type": "string"
		},
		"language": {
			"type": "object",
			"properties": {
				"iso": {
					"type": "object",
					"properties": {
						"code": {
							"type": "string"
						},
						"name": {
							"type": "string"
						}
					},
					"required": [
						"code",
						"name"
					],
					"additionalProperties": false
				},
				"culture": {
					"type": "string"
				}
			},
			"required": [
				"iso",
				"culture"
			],
			"additionalProperties": false
		},
		"url": {
			"type": "object",
			"properties": {
				"api": {
					"type": "object",
					"properties": {
						"restful": {
							"type": "string"
						},
						"static": {
							"type": "string"
						}
					},
					"required": [
						"restful",
						"static"
					],
					"additionalProperties": false
				},
				"logo": {
					"type": "string"
				},
				"application": {
					"type": "string"
				}
			},
			"required": [
				"api",
				"logo",
				"application"
			],
			"additionalProperties": false
		},
		"dataset": {
			"type": "object",
			"properties": {
				"officialStatistics": {
					"type": "boolean"
				},
				"download": {
					"type": "object",
					"properties": {
						"threshold": {
							"type": "object",
							"properties": {
								"csv": {
									"type": "integer"
								},
								"xlsx": {
									"type": "integer"
								}
							},
							"required": [
								"csv",
								"xlsx"
							],
							"additionalProperties": false
						}
					},
					"required": [
						"threshold"
					],
					"additionalProperties": false
				},
				"analytical": {
					"type": "object",
					"properties": {
						"label": {
							"type": "string"
						},
						"icon": {
							"type": "string"
						},
						"colour": {
							"type": "string"
						},
						"display": {
							"type": "boolean"
						}
					},
					"required": [
					"label",
					"icon",
					"colour",
					"display"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"officialStatistics",
				"download",
				"analytical"
			],
			"additionalProperties": false
		},
		"regex": {
			"type": "object",
			"properties": {
				"phone": {
					"type": "object",
					"properties": {
						"pattern": {
							"type": "string"
						},
						"placeholder": {
							"type": "string"
						}
					},
					"required": [
						"pattern",
						"placeholder"
					],
					"additionalProperties": false
				},
				"password": {
					"type": "string"
				},
				"matrix-name": {
					"type": "string"
				},
				"product-code": {
					"type": "string"
				}
			},
			"required": [
				"phone",
				"password",
				"matrix-name",
				"product-code"
			],
			"additionalProperties": false
		},
		"workflow": {
			"type": "object",
			"properties": {
				"embargo": {
					"type": "object",
					"properties": {
						"time": {
							"type": "string",
							"pattern": "^(?:([01]?\\d|2[0-3]):([0-5]?\\d):)?([0-5]?\\d)$"
						},
						"day": {
							"type": "array",
							"items": [
								{
									"type": "integer"
								}
							],
							"maxItems":5,
							"minItems":5
						}
					},
					"required": [
						"time",
						"day"
					],
					"additionalProperties": false
				},
				"fastrack": {
					"type": "object",
					"properties": {
						"response": {
							"type": "object",
							"properties": {
								"approver": {
									"type": "boolean"
								},
								"poweruser": {
									"type": "boolean"
								},
								"administrator": {
									"type": "boolean"
								}
							},
							"required": [
								"approver",
								"poweruser",
								"administrator"
							],
							"additionalProperties": false
						},
						"signoff": {
							"type": "object",
							"properties": {
								"poweruser": {
									"type": "boolean"
								},
								"administrator": {
									"type": "boolean"
								}
							},
							"required": [
								"poweruser",
								"administrator"
							],
							"additionalProperties": false
						}
					},
					"required": [
						"response",
						"signoff"
					],
					"additionalProperties": false
				},
				"release": {
					"type": "object",
					"properties": {
						"reasonRequired": {
							"type": "boolean"
						}
					},
					"required": [
						"reasonRequired"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"embargo",
				"fastrack",
				"release"
			],
			"additionalProperties": false
		},
		"build": {
			"type": "object",
			"properties": {
				"create": {
					"type": "object",
					"properties": {
						"moderator": {
							"type": "boolean"
						}
					},
					"required": [
						"moderator"
					],
					"additionalProperties": false
				},
				"update": {
					"type": "object",
					"properties": {
						"moderator": {
							"type": "boolean"
						}
					},
					"required": [
						"moderator"
					],
					"additionalProperties": false
				},
				"import": {
					"type": "object",
					"properties": {
						"moderator": {
							"type": "boolean"
						}
					},
					"required": [
						"moderator"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"create",
				"update",
				"import"
			],
			"additionalProperties": false
		},
		"session": {
			"type": "object",
			"properties": {
				"length": {
					"type": "integer"
				}
			},
			"required": [
				"length"
			],
			"additionalProperties": false
		},
		"security": {
			"type": "object",
			"properties": {
				"adOpenAccess": {
					"type": "boolean"
				},
				"demo": {
					"type": "boolean"
				},
                 "tokenApiAccessIpMaskWhitelist": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "prefix": {
                  "type": "string"
                },
                "length": {
                  "type": "integer"
                }
              },
              "required": [
                "prefix",
                "length"
              ]
            }
          ]
        }
			},
			"required": [
				"adOpenAccess",
				"demo",
              "tokenApiAccessIpMaskWhitelist" 
			],
			"additionalProperties": false
		},
		"search": {
			"type": "object",
			"properties": {
				"maximumResults": {
					"type": "integer"
				}
			},
			"required": [
				"maximumResults"
			],
			"additionalProperties": false
		},
		"report": {
			"type": "object",
			"properties": {
				"date-validation": {
					"type": "object",
					"properties": {
						"minDate": {
							"type": "integer"
						},
						"maxDate": {
							"type": "integer"
						}
					},
					"required": [
						"minDate",
						"maxDate"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"date-validation"
			],
			"additionalProperties": false
		},
		"salsa": {
			"type": "object",
			"properties": {
				"firebase" :{
					"type": "string"
				},
				"pxstat": {
					"type": "string"
				}
				
			}
		}

	},
	"required": [
		"title",
		"language",
		"url",
		"dataset",
		"regex",
		"workflow",
		"build",
		"session",
		"security",
		"search",
		"report"
	],
	"additionalProperties": false
}

=== CSOIreland/PxStat/server/build/PxStatCore.Test/Resources/test8.json
{
  "title": "",
  "language": {
    "iso": {
      "code": "en",
      "name": "English"
    },
    "culture": "en-ie"
  },
  "url": {
    "api": {
      "restful": "",
      "static": ""
    },
    "logo": "https://cdn.test.ie/static/img/cso_logo_312_x_108_96dpi.png",
    "application": ""
  },
  "dataset": {
    "officialStatistics": true,
    "download": {
      "threshold": {
        "csv": 1048573,
        "xlsx": 1048575
      }
    },
    "analytical": {
      "label": "dependency",
      "icon": "fa-solid fa-circle-nodes",
      "colour": "text-analytical",
      "display": false
    }
  },
  "regex": {
    "phone": {
      "pattern": "^(\\(\\+\\d{1,3}\\) \\d+ \\d+ \\d+)$",
      "placeholder": "(+353) 21 452 2253"
    },
    "password": "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\\W]).{8,}$",
    "matrix-name": "^[A-Z0-9]+$",
    "product-code": "^[a-zA-Z0-9]+$"
  },
  "workflow": {
    "embargo": {
      "time": "11:00:00",
      "day": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    "fastrack": {
      "response": {
        "approver": true,
        "poweruser": true,
        "administrator": false
      },
      "signoff": {
        "poweruser": true,
        "administrator": false
      }
    },
    "release": {
      "reasonRequired": true
    }
  },
  "build": {
    "create": {
      "moderator": false
    },
    "update": {
      "moderator": true
    },
    "import": {
      "moderator": true
    }
  },
  "session": {
    "length": 1200
  },
  "security": {
    "adOpenAccess": false,
    "demo": false,
    "tokenApiAccessIpMaskWhitelist": [
      {
        "prefix": "3.0.0.0",
        "length": 12
      },
      {
        "prefix": "::1",
        "length": 32
      }
    ]
  },
  "search": {
    "maximumResults": 101
  },
  "report": {
    "date-validation": {
      "minDate": 365,
      "maxDate": -1
    }
  }
}
